[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600        ; Upload via kabel lebih cepat
upload_protocol = esptool    ; Kembali ke metode kabel
; upload_port = COM6         ; (Opsional) Ganti dengan COM port ESP-mu jika perlu