[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool

lib_deps = bodmer/TFT_eSPI@^2.5.43

build_flags = 
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2        ; ⚠️ Digeser dari 17 agar tidak bentrok dengan RS485 TX
    -D TFT_RST=4
    -D LOAD_GLCD=1
    -D SPI_FREQUENCY=27000000