[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    https://github.com/coryjfowler/MCP_CAN_lib.git

# ✅ Tambahan untuk Static Analysis
;check_tool = cppcheck, clangtidy
;check_flags =
;    cppcheck: --enable=warning,performance,portability --inline-suppr